from enum import Enum

class ReturnCode(Enum):
	OK = 0
	WRONG_PARAMETER = 1
	UNAUTHORIZED_PRIVATE_KEY = 2
	EMPTY_CHAIN = 4
	WRONG_CHAIN_HEIGHT_NUMBER = 5
	INVALID_ARGUMENT = 6
	INVALID_TRANSACTION = 7
	INVALID_SIGNATURE = 8
	CARGO_ID_NOT_FOUND = 9